name: Pre-commit checks

on:
  pull_request:
    branches:
      - main # or the branch you want to protect
  push:
    branches:
      - main # or the branch you want to protect

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Use the same version as specified in your pre-commit config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install sqlfluff dbt-core==1.8.3 dbt-postgres==1.8.2
          pip install -r requirements.txt  # If you have additional requirements
          pip install dbt

      - name: Run dbt compile
        run: |
          cd dbt_proj_03
          dbt compile

      - name: Run pre-commit
        run: pre-commit run --all-files
